### ISSUE TITLE
practica de operaciones basicas 

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-elisa1223#1]
[practica_elisa sanchez coronel_1AS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-elisa1223/files/12564607/practica_elisa.sanchez.coronel_1AS.pdf)

**Comment by Maricruz-Gomz** [comment]
Portada 25
Procedimiento 25
Ilustraciones, figuras y fotografías 15
Resultados y conclusiones 25
Calificación: 18/20%
Calificado por: Anais Martínez y Mari cruz Gomez

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
